python bitwise_complete_generator.py 50000 10 Ensemble/models/bitwise_complete.json 0
python bitwise_complete_generator.py 50000 10 Ensemble/models/bitwise_complete.json 1
python bitwise_complete_generator.py 50000 10 Ensemble/models/bitwise_complete.json 2
python bitwise_complete_generator.py 50000 10 Ensemble/models/bitwise_complete.json 3
python bitwise_complete_generator.py 50000 10 Ensemble/models/bitwise_complete.json 4
python bitwise_complete_generator.py 50000 10 Ensemble/models/bitwise_complete.json 5
python bitwise_complete_generator.py 50000 10 Ensemble/models/bitwise_complete.json 6
python bitwise_complete_generator.py 50000 10 Ensemble/models/bitwise_complete.json 7
python bitwise_complete_generator.py 50000 10 Ensemble/models/bitwise_complete.json 8
python bitwise_complete_generator.py 50000 10 Ensemble/models/bitwise_complete.json 9
python bitwise_complete_generator.py 50000 10 Ensemble/models/bitwise_complete.json 10
python bitwise_complete_generator.py 50000 10 Ensemble/models/bitwise_complete.json 11
