python bitwise_complete_generator.py 50000 10 Ensemble/models/non_regional_paths_only.json 0
python bitwise_complete_generator.py 50000 10 Ensemble/models/non_regional_paths_only.json 1
python bitwise_complete_generator.py 50000 10 Ensemble/models/non_regional_paths_only.json 2
python bitwise_complete_generator.py 50000 10 Ensemble/models/non_regional_paths_only.json 3
python bitwise_complete_generator.py 50000 10 Ensemble/models/non_regional_paths_only.json 4
python bitwise_complete_generator.py 50000 10 Ensemble/models/non_regional_paths_only.json 5
python bitwise_complete_generator.py 50000 10 Ensemble/models/non_regional_paths_only.json 6
python bitwise_complete_generator.py 50000 10 Ensemble/models/non_regional_paths_only.json 7
python bitwise_complete_generator.py 50000 10 Ensemble/models/non_regional_paths_only.json 8
python bitwise_complete_generator.py 50000 10 Ensemble/models/non_regional_paths_only.json 9
python bitwise_complete_generator.py 50000 10 Ensemble/models/non_regional_paths_only.json 10
python bitwise_complete_generator.py 50000 10 Ensemble/models/non_regional_paths_only.json 11
python bitwise_complete_generator.py 50000 10 Ensemble/models/non_regional_paths_only.json 12
python bitwise_complete_generator.py 50000 10 Ensemble/models/non_regional_paths_only.json 13
python bitwise_complete_generator.py 50000 10 Ensemble/models/non_regional_paths_only.json 14
python bitwise_complete_generator.py 50000 10 Ensemble/models/non_regional_paths_only.json 15
python bitwise_complete_generator.py 50000 10 Ensemble/models/non_regional_paths_only.json 16
python bitwise_complete_generator.py 50000 10 Ensemble/models/non_regional_paths_only.json 17
python bitwise_complete_generator.py 50000 10 Ensemble/models/non_regional_paths_only.json 18
python bitwise_complete_generator.py 50000 10 Ensemble/models/non_regional_paths_only.json 19
python bitwise_complete_generator.py 50000 10 Ensemble/models/non_regional_paths_only.json 20
python bitwise_complete_generator.py 50000 10 Ensemble/models/non_regional_paths_only.json 21
python bitwise_complete_generator.py 50000 10 Ensemble/models/non_regional_paths_only.json 22
python bitwise_complete_generator.py 50000 10 Ensemble/models/non_regional_paths_only.json 23
python bitwise_complete_generator.py 50000 10 Ensemble/models/non_regional_paths_only.json 24
python bitwise_complete_generator.py 50000 10 Ensemble/models/non_regional_paths_only.json 25
python bitwise_complete_generator.py 50000 10 Ensemble/models/non_regional_paths_only.json 26
python bitwise_complete_generator.py 50000 10 Ensemble/models/non_regional_paths_only.json 27
python bitwise_complete_generator.py 50000 10 Ensemble/models/non_regional_paths_only.json 28
python bitwise_complete_generator.py 50000 10 Ensemble/models/non_regional_paths_only.json 29
python bitwise_complete_generator.py 50000 10 Ensemble/models/non_regional_paths_only.json 30
python bitwise_complete_generator.py 50000 10 Ensemble/models/non_regional_paths_only.json 31
python bitwise_complete_generator.py 50000 10 Ensemble/models/non_regional_paths_only.json 32
python bitwise_complete_generator.py 50000 10 Ensemble/models/non_regional_paths_only.json 33
python bitwise_complete_generator.py 50000 10 Ensemble/models/non_regional_paths_only.json 34
python bitwise_complete_generator.py 50000 10 Ensemble/models/non_regional_paths_only.json 35
python bitwise_complete_generator.py 50000 10 Ensemble/models/non_regional_paths_only.json 36
python bitwise_complete_generator.py 50000 10 Ensemble/models/non_regional_paths_only.json 37
python bitwise_complete_generator.py 50000 10 Ensemble/models/non_regional_paths_only.json 38
python bitwise_complete_generator.py 50000 10 Ensemble/models/non_regional_paths_only.json 39
python bitwise_complete_generator.py 50000 10 Ensemble/models/non_regional_paths_only.json 40
python bitwise_complete_generator.py 50000 10 Ensemble/models/non_regional_paths_only.json 41
python bitwise_complete_generator.py 50000 10 Ensemble/models/non_regional_paths_only.json 42
python bitwise_complete_generator.py 50000 10 Ensemble/models/non_regional_paths_only.json 43
