python conditional_generator.py 50000 10 Ensemble/models/patterns/F4_A_with_triplets.json 0
python conditional_generator.py 50000 10 Ensemble/models/patterns/F4_A_with_triplets.json 1
python conditional_generator.py 50000 10 Ensemble/models/patterns/F4_A_with_triplets.json 2
python conditional_generator.py 50000 10 Ensemble/models/patterns/F4_A_with_triplets.json 3
python conditional_generator.py 50000 10 Ensemble/models/patterns/F4_A_with_triplets.json 4
python conditional_generator.py 50000 10 Ensemble/models/patterns/F4_A_with_triplets.json 5
python conditional_generator.py 50000 10 Ensemble/models/patterns/F4_A_with_triplets.json 6
python conditional_generator.py 50000 10 Ensemble/models/patterns/F4_A_with_triplets.json 7
python conditional_generator.py 50000 10 Ensemble/models/patterns/F4_A_with_triplets.json 8
python conditional_generator.py 50000 10 Ensemble/models/patterns/F4_A_with_triplets.json 9
python conditional_generator.py 50000 10 Ensemble/models/patterns/F4_A_with_triplets.json 10
python conditional_generator.py 50000 10 Ensemble/models/patterns/F4_A_with_triplets.json 11
python conditional_generator.py 50000 10 Ensemble/models/patterns/F4_A_with_triplets.json 12
python conditional_generator.py 50000 10 Ensemble/models/patterns/F4_A_with_triplets.json 13
python conditional_generator.py 50000 10 Ensemble/models/patterns/F4_A_with_triplets.json 14
python conditional_generator.py 50000 10 Ensemble/models/patterns/F4_A_with_triplets.json 15
python conditional_generator.py 50000 10 Ensemble/models/patterns/F4_B_with_triplets.json 0
python conditional_generator.py 50000 10 Ensemble/models/patterns/F4_B_with_triplets.json 1
python conditional_generator.py 50000 10 Ensemble/models/patterns/F4_B_with_triplets.json 2
python conditional_generator.py 50000 10 Ensemble/models/patterns/F4_B_with_triplets.json 3
python conditional_generator.py 50000 10 Ensemble/models/patterns/F4_B_with_triplets.json 4
python conditional_generator.py 50000 10 Ensemble/models/patterns/F4_B_with_triplets.json 5
python conditional_generator.py 50000 10 Ensemble/models/patterns/F4_B_with_triplets.json 6
python conditional_generator.py 50000 10 Ensemble/models/patterns/F4_B_with_triplets.json 7
python conditional_generator.py 50000 10 Ensemble/models/patterns/F4_B_with_triplets.json 8
python conditional_generator.py 50000 10 Ensemble/models/patterns/F4_B_with_triplets.json 9
python conditional_generator.py 50000 10 Ensemble/models/patterns/F4_B_with_triplets.json 10
python conditional_generator.py 50000 10 Ensemble/models/patterns/F4_B_with_triplets.json 11
python conditional_generator.py 50000 10 Ensemble/models/patterns/F4_B_with_triplets.json 12
python conditional_generator.py 50000 10 Ensemble/models/patterns/F4_B_with_triplets.json 13
python conditional_generator.py 50000 10 Ensemble/models/patterns/F4_B_with_triplets.json 14
python conditional_generator.py 50000 10 Ensemble/models/patterns/F4_B_with_triplets.json 15
python conditional_generator.py 50000 10 Ensemble/models/patterns/NCG_with_triplets.json 0
python conditional_generator.py 50000 10 Ensemble/models/patterns/NCG_with_triplets.json 1
python conditional_generator.py 50000 10 Ensemble/models/patterns/NCG_with_triplets.json 2
python conditional_generator.py 50000 10 Ensemble/models/patterns/NCG_with_triplets.json 3
python conditional_generator.py 50000 10 Ensemble/models/patterns/NCG_with_triplets.json 4
python conditional_generator.py 50000 10 Ensemble/models/patterns/NCG_with_triplets.json 5
python conditional_generator.py 50000 10 Ensemble/models/patterns/NCG_with_triplets.json 6
python conditional_generator.py 50000 10 Ensemble/models/patterns/NCG_with_triplets.json 7
python conditional_generator.py 50000 10 Ensemble/models/patterns/NCG_with_triplets.json 8
python conditional_generator.py 50000 10 Ensemble/models/patterns/NCG_with_triplets.json 9
python conditional_generator.py 50000 10 Ensemble/models/patterns/NCG_with_triplets.json 10
python conditional_generator.py 50000 10 Ensemble/models/patterns/NCG_with_triplets.json 11
python conditional_generator.py 50000 10 Ensemble/models/patterns/NCG_with_triplets.json 12
python conditional_generator.py 50000 10 Ensemble/models/patterns/NCG_with_triplets.json 13
python conditional_generator.py 50000 10 Ensemble/models/patterns/NCG_with_triplets.json 14
python conditional_generator.py 50000 10 Ensemble/models/patterns/NCG_with_triplets.json 15
