python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 0
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 1
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 2
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 3
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 4
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 5
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 6
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 7
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 8
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 9
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 10
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 11
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 12
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 13
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 14
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 15
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 16
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 17
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 18
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 19
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 20
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 21
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 22
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 23
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 24
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 25
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 26
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 27
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 28
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 29
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 30
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 31
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 32
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 33
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 34
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 35
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 36
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 37
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 38
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 39
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 40
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 41
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 42
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 43
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 44
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 45
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 46
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 47
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 48
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 49
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 50
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 51
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 52
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 53
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 54
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 55
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 56
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 57
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 58
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 59
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 60
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 61
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 62
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 63
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 64
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 65
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 66
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 67
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 68
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 69
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 70
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 71
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 72
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 73
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 74
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 75
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 76
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 77
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 78
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 79
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 80
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 81
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 82
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 83
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 84
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 85
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 86
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 87
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 88
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 89
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 90
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 91
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 92
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 93
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 94
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 95
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 96
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 97
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 98
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 99
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 100
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 101
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 102
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 103
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 104
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 105
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 106
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 107
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 108
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 109
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 110
python bitwise_complete_generator.py 50000 10 Ensemble/models/patterns/all_triplets.json 111
